# https://github.com/andreashuber69/capped-promise#--
os: linux
dist: xenial
language: node_js
node_js:
- 16

branches:
  only:
  - develop
  - /^release\/.*/
  - master

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- npm run ci

after_script:
- ./cc-test-reporter format-coverage --input-type lcov ./coverage/lcov.info
- ./cc-test-reporter upload-coverage --id $CODECLIMATE_TEST_REPORTER_ID
- export CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage
- export CODECLIMATE_REPO_TOKEN=fd40f089-dc96-44ab-b45b-7f12f0936bee
- npx codeclimate-test-reporter < coverage/lcov.info

deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: mQMBAXV/bwyLqB0fPi9OBzSf1JuBEiJ147jW0plRFs1MaI/pg8XbxhM7Qw/i8HC0HwxJjDreo90IHTfP9Zqy0gTdh/tUMPRbMIF5V7OlZ2doTcHbvS7dvZl6sK5dWp7L3ND+gYn1R0B0096LCIpxc4wCb3Pb6lkXV/EvMogca2AQDNlfMoOenPXHCzSJjBJZND9enjcmuaCKph9aLXIhkf9fcvw+FoglLi5J6mtMUp1wtO2zXhvbRVmflfsYqfOpJryBGU7EmJjA57/kNw6mTF/9Y9PDK/0v3HlNNvJexiriyltSTUJ3kmGnZJpwsCllJ0XthicRSs6MdLLr0CSMyR0Q185v+w7EIGtLya/zJsrB7wq4WRKZbLUudVuCUXfDB3+HmE0CqBnNVAMkR8NQwi6dU4Q6sToY8YeXT4+QOLuPpMgP2xDFPg+2YO2WzSCETZQVMtZ0zqMXRezFy2QlfYdthIXeSK0MHNJ2jcDiwB+KhhjrmVrW86IMwhA6NHz7qgeJRdu/f098X0O/YwlI7bIhjxRATojPOt5CXeNNablwFrcCXEEmVy6TtBcSHdBsiVVs+l9VY5yC7ySGJUlEOEIRcOffrXjZ6MG28I+0dYkGu/mEJmgVIiUe7nZ4YaLQanEsLKyRfdS6HhB0hA8A3xqiAXyRoe263P1zKG3eGOk=
  api_token:
    secure: jv/m3iuReyu6Av5u17rREh8PwnHHRNp2GP5yfuRTP56V00LsbpO/leQOltzgrPtV2WODc250bOhKXaAnKXTbsLILyR5mmYziJbUjN/PmpdAWnoJAJiD68Btdf2t5ozFuhc+gV3FMchXFgAu5cyQv48C30zQFx1hwKYRGraGy6excA5+jC1ug1P5JNBTGkrWc0L0yVStd1L9HSbsLBaTI9z66out292aNaS5nS6cyv+mR2fTMcxIgKMyliFAFSOsskLfMbNBj8bQL1nqSTunYmeZNE5Qrm5RBZufW2CbZ5ZYSTCF5hH4/Dd7jxdT2axnAIkNX/KlwBAcXCBydCnKcRN4EitjDX+5xSR6ki3PlP6LgIXTWkO/sjors4FgaacC7ZutTk+qvuAVPKDKWPtALWs6XTSIrs3/OJA5v4RCb0dmLOqLIxslB//sF6Knb5E3e+Abx0dzYysHuPf46GdjnRTz5imAV+yHa62asLimtSypXGLR1xcKn1LP/gpsJgaJRJm2LPuH6fuABSbt3rMWweMeKlO6/ejtAPotg1PBVTbCnI4ufc2Eq2A3YWU2HkAfiYXL6/N4rqhyUrEgHhdy7V9W5VXSmWy5BywbgJR3dYmypgOhM5xIjIv8ouSZTWqiIuSqni+hZiPPmyorEXRPlMJD3HWgI7lWvA7oCvFUWlbk=
  on:
    branch: master

notifications:
  email:
    recipients:
    - secure: TUq7JdVGdyqa1uMkPgUbIhTxAPAitc1+csF8crqnhsqETuXByBjgKlnGpYGJrU9VUTQijPTELNLeOhG30bQBqrsaKSj/Z0jXKMze3mTLB65xskR0d9rsShQZUksVModiiaB1KHG8HoN779m27H3JEnCW9KfcwplQmUTtWnsKdfLrclCqmxNQjC/QCw8RHbpv5viPB2uztRK0OD9rFUUN+dfH4+VQUZ5p+BtXhUxnnLL2AeFc/ZwupjaBstEo8TlPYO747vqGgKUgJFn3XlaiOfGL2ShcDKMoQqRiXsaRqS5NOlettWeImF2/R0A3IQi6L8QH5REWtNF6QwK962xFAjVFYOiF93+v8qW/rotf1AbmDH7ydn8OrR7odl09jdFIx587fO5yNXYxEqV20rO+2ZFzAuxMZBSwIdIayzkkfjPXcnGucjvQnH7eVCmXL54Gyeykpa68BvhoUTuNHCllFzdvnpg1Q5+uxeoaZMV+Go33AMITfuX6zmXocvE6escrhERVlICLKtnFBJzGAsKIEUWlnK+tnQjNVdedGvqC/G6bitAGkxGAuz8iQnAYsnucLaCpyZ/4ANuMw9MT4Kck6eFFhQX7JWJXUhCuv8ls7BGfYb/AopmdIC2MngYctixyAV0H+qK+iA3bUEw+LLarc1Df6/ylosJexnyNTkN5OQQ=
